### ISSUE TITLE
NUnit 3 is RTM - it's time to fix CADtest

### ISSUE THREAD

**Issue by CADbloke** [CADbloke/CADtest#5]
I aim to get CADtest fixed and fit for consumption by mid-January 2016. I am starting on www.tvCAD.tv soon and I certainly plan on testing that code. 

The code here will mainly serve as an example or a kick-starter snippet at the most - the real usefulness will the the How-to wiki...how to add a CADtest project and set it up.

**Comment by phliberato** [comment]
Can I use Cadtest in Test Explorer of Visual Studio with Nunit adapter?

**Comment by CADbloke** [comment]
@phliberato Nope - You can't run it out of the AutoCAD process, that's why we need CADtest in the first place. I know you have worked that out yourself by now, this answer is for others who find this question.

Also, it works now - until I touch it again.
